---
#========================
# File tasks/main.yml
#
# Description: Installs and Configures nginx on a deb based server
#
# Author: Derek 'dRock' Halsey
#========================

- name: APT_REPOSITORY | Add PPA repository for certbot
  become: true
  become_user: root
  apt_repository:
    repo: 'ppa:certbot/certbot'
    update_cache: true

- name: APT | Ensure Nginx and Certbot are installed on the system
  become: true
  become_user: root
  apt:
    update_cache: true
    name: "{{ item }}"
  with_items:
  - nginx
  - certbot

- name: FILE | Remove default nginx website and config files
  become: true
  become_user: root
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /var/www/html
  - /etc/nginx/sites-available/default
  - /etc/nginx/sites-enabled/default

- name: TEMPLATE | Template the nginx.conf file
  become: true
  become_user: root
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: STAT | Check if dhparam cert exists
  stat:
    path: /etc/ssl/dhparam.pem
  register: nginx_dhparam

- name: COMMAND | Generate dhparam cert
  become: true
  become_user: root
  command: openssl dhparam -out /etc/ssl/dhparam.pem 2048
  when: not nginx_dhparam.stat.exists

- name: SERVICE | Ensure nginx is started and enabled
  become: true
  become_user: root
  service:
    name: nginx
    state: started
    enabled: true


- name: COMMAND | Reload nginx
  become: true
  become_user: root
  command: nginx -s reload
